services:
  ptudhttthd-web-hrm.server:
    image: ptudhttthd-web-hrm.server
    container_name: web-hrm.server
    build:
      context: .
      dockerfile: ptudhttthd-web-hrm.Server/Dockerfile

  MSSQL:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: MSSQL
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong#Passw0rd123
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools18/bin/sqlcmd","-C", "-S", "localhost", "-U", "sa", "-P", "YourStrong#Passw0rd123", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
volumes:
  mssql_data: